### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Nomis9** [CokeCookie/RollTrackerClassic#1]
Hello,
will you release any fixed version in the future?
CSV export click ->

> 1x RollTrackerClassic\LibGPIToolBox.lua:734: attempt to call method 'SetBackdrop' (a nil value)
> [string "@RollTrackerClassic\LibGPIToolBox.lua"]:734: in function <RollTrackerClassic\LibGPIToolBox.lua:731>
> [string "@RollTrackerClassic\LibGPIToolBox.lua"]:825: in function `CopyPast'
> [string "@RollTrackerClassic\RollTrackerClassic-2.21-bcc.lua"]:1719: in function `BtnExport'
> [string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
> 
> Locals:
> frame = <unnamed> {
>  0 = <userdata>
> }
> (*temporary) = nil
> (*temporary) = <unnamed> {
>  0 = <userdata>
> }
> (*temporary) = <table> {
>  bgFile = "Interface/DialogFrame/UI-DialogBox-Background"
>  tile = true
>  edgeFile = "Interface/DialogFrame/UI-DialogBox-Border"
>  edgeSize = 32
>  insets = <table> {
>  }
> }
> (*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
> CopyPastFrame = nil
> CopyPastText = nil
> Tool = <table> {
>  Split = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:308
>  CreatePopup = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:512
>  SlashCommand = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:712
>  EnableHyperlink = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:88
>  IconClassTexture = "GLUES\CHARACTERCREATE\UI-CHARACTERCREATE-CLASSES"
>  OnUpdate = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:123
>  AddTab = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:585
>  EnableMoving = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:147
>  UnitDistanceSquared = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:198
>  Classes = <table> {
>  }
>  ClassName = <table> {
>  }
>  Combine = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:282
>  RaidIconNames = <table> {
>  }
>  NameToClass = <table> {
>  }
>  EnableSize = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:371
>  TabHide = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:542
>  PrintSlashCommand = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:653
>  AddDataBrocker = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:623
>  IconClassTextureCoord = <table> {
>  }
>  RunSlashCmd = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:167
>  GetRaidIcon = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:193
>  RaidIcon = <table> {
>  }
>  stripChars = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:258
>  IconClassBig = <table> {
>  }
>  TabShow = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:552
>  CreatePattern = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:262
>  CopyPast = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:823
>  RegisterEvent = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:111
>  GetSelectedTab = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:574
>  SelectTab = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:562
>  TabOnSelect = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:568
>  iSplit = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:295
>  RGBtoEscape = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:178
>  GuildNameToIndex = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:158
>  IconClassTextureWithoutBorder = "WorldStateFrame\ICONS-CLASSES"
>  IconClass = <table> {
>  }
>  iMerge = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:242
>  ClassColor = <table> {
>  }
>  Merge = <function> defined @RollTrackerClassic\LibGPIToolBox.lua:233
> }
> CopyPastSavedText = nil

**Comment by CokeCookie** [comment]
Sorry to keep you waiting. I haven't looked at this repo since TBC release and just now noticed your issue. 
Should be fixed in the newest release. Have fun!
